test fix
0xProject/0x-event-pipeline pull request #160
Opened 2024-10-09 20:39 UTC by 0xyijing

2024-10-10 15:09 UTC, nicoalencar commented on src/scripts/pull_and_save_block_events.ts
> +            const allowedTxnListQuery = await connection.query(
I'm not sure if I understand correctly the PR. 

So basically we are checking for missing txs in the backfill process for each block?
and if we detect, we retrieve them on the filter function?

That solves 100% of the issue?

2024-10-10 18:26 UTC, nicoalencar approved these changes

2024-10-10 23:06 UTC, AndresElizondo requested changes
Restore the docker-compose before merging, please

2024-10-25 16:00 UTC, 0xyijing commented
> Restore the docker-compose before merging, please

@AndresElizondo will do but fyi that's docker-compose.dev for local

2024-11-08 12:26 UTC, AndresElizondo commented
Renaming PR to have a descriptive name.

2024-11-08 12:27 UTC, merged